# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 22:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('lectura_critica', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('matematicas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('sociales', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('naturales', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('ingles', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('razonamiento_cuantitativo', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('competencias_ciudadanas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
